name: 'Backend CI/CD'

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/ie-bank-backend.yml'

env:
  BACKEND_WEBAPP_DEV: #Exercise IV: set the name of your web app
  IMAGE_NAME: #Exercise IV: set the name of container image
  REGISTRY_USERNAME: #Exercise IV: set the user name credentials of your container registry
  REGISTRY_PASSWORD: #Exercise IV: set the user name credentials of your container registry

jobs:
  build:
    
    runs-on: ubuntu-latest
    env:
      ENV: ghci

    steps:
      # Exercise IV
      # GitHub action: Write step to checkout code.

      # Exercise IV
      # GitHub action: Write step to set up Python 3.11.

      # Exercise IV
      # GitHub action: Write step to upgrade Python pip. Consider using the `working-directory: ./backend` setting
    
      # Exercise IV
      # GitHub action: Write step to install dependencies with pip. Consider using the `working-directory: ./backend` setting

      # Exercise IV
      # GitHub action: Write step to install flake8 and pytest, and use flake8 to check code syntax. Consider using the `working-directory: ./backend` setting

      # Exercise IV
      # GitHub action: Write step to run python tests with pytest. Consider using the `working-directory: ./backend` setting
    
      # Exercise IV
      # GitHub action: Write step to login in to Azure Container Registry.
      # Use the GitHub repository secrets REGISTRY_USERNAME and REGISTRY_PASSWORD. Get the values from the Azure portal
      
      # Exercise IV
      # GitHub action: Write step to set your docker image version
      # You can use the environment variable IMAGE_NAME

      #Exercise IV
      # GitHub action: Write step to build and push your Docker image into the Container Registry

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:
      # Exercise IV
      # GitHub action: Write step to login in to Azure.
      # You can use the repository secret AZURE_CREDENTIALS

      # Exercise IV
      # GitHub action: Write step to set up the published container image for your Azure container web app
    