name: 'Backend CI/CD'

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/ie-bank-backend.yml'

env:
  BACKEND_WEBAPP_DEV: #Exercise IV: set the name of your web app
  IMAGE_NAME: #Exercise IV: set the name of container image
  REGISTRY_USERNAME: #Exercise IV: set the user name credentials of your container registry
  REGISTRY_PASSWORD: #Exercise IV: set the user name credentials of your container registry

jobs:
  build:
    
    runs-on: ubuntu-latest
    env:
      ENV: ghci

    steps:


      # Exercise IV
      # GitHub action: Write step to checkout code.
      - uses: actions/checkout@main

      # Exercise IV
      # GitHub action: Write step to set up Python 3.11.
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11

      # Exercise IV
      # GitHub action: Write step to upgrade Python pip. Consider using the `working-directory: ./backend` setting
      - name: Upgrade Python pip
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip


      # Exercise IV
      # GitHub action: Write step to install dependencies with pip. Consider using the `working-directory: ./backend` setting
      - name: Install dependencies
        run: |
          pip install -r ./backend/requirements.txt    
      # Exercise IV
      # GitHub action: Write step to install flake8 and pytest, and use flake8 to check code syntax. Consider using the `working-directory: ./backend` setting
      - name: Lint with flake8
        working-directory: ./backend
        run: |
          pip install flake8 pytest
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      # Exercise IV
      # GitHub action: Write step to run python tests with pytest. Consider using the `working-directory: ./backend` setting
      - name: Test with pytest
        working-directory: ./backend
        run: |
          python -m pytest --cov=iebank_api -v
      # Exercise IV
      # GitHub action: Write step to login in to Azure Container Registry.
      # Use the GitHub repository secrets REGISTRY_USERNAME and REGISTRY_PASSWORD. Get the values from the Azure portal
      
      # Exercise IV
      # GitHub action: Write step to set your docker image version
      # You can use the environment variable IMAGE_NAME

      #Exercise IV
      # GitHub action: Write step to build and push your Docker image into the Container Registry

  
      # Exercise IV
      # GitHub action: Write step to login in to Azure.
      # You can use the repository secret AZURE_CREDENTIALS

      # Exercise IV
      # GitHub action: Write step to set up the published container image for your Azure container web app
    